/**
 * wecon postman
 * 
 * Generate Postman collection from the project
 */

import { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import path from "path";
import fs from "fs-extra";
import { execSync } from "child_process";

export const postmanCommand = new Command("postman")
  .description("Generate Postman collection")
  .option("--env <env>", "Environment to use", "development")
  .option("-o, --output <path>", "Output directory", "./postman")
  .action(async (options) => {
    const spinner = ora("Generating Postman collection...").start();

    try {
      const projectRoot = process.cwd();
      
      // Ensure we are in a Wecon project
      if (!fs.existsSync(path.join(projectRoot, "wecon.config.ts"))) {
        throw new Error("wecon.config.ts not found. Are you in a Wecon project?");
      }

      // Create output directory
      const outputDir = path.resolve(projectRoot, options.output);
      fs.ensureDirSync(outputDir);

      const scriptContent = `
import { wecon } from "./src/bootstrap.js";
import { loadConfig } from "@weconjs/core";
import path from "path";
import fs from "fs";

async function generate() {
  try {
    const configPath = path.resolve(process.cwd(), "wecon.config.ts");
    const config = await loadConfig(configPath, "${options.env}");

    // Try multiple methods to generate postman collection
    let collection = null;
    let environment = null;

    // Method 1: Check if wecon has generatePostmanCollection
    if (typeof wecon.generatePostmanCollection === 'function') {
      const result = await wecon.generatePostmanCollection();
      collection = result.collection || result;
      environment = result.environment;
    }
    // Method 2: Check for postman property with generate method
    else if (wecon.postman && typeof wecon.postman.generate === 'function') {
      const result = await wecon.postman.generate();
      collection = result.collection || result;
      environment = result.environment;
    }
    // Method 3: Build collection manually from routes
    else if (wecon.routes || wecon._routes) {
      const routes = wecon.routes || wecon._routes;
      collection = buildCollectionFromRoutes(routes, config);
      environment = buildEnvironment(config);
    }
    else {
      console.log("No Postman generation method found. Creating basic collection from routes...");
      collection = {
        info: {
          name: config.app?.name || "Wecon API",
          schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
        },
        item: []
      };
      environment = buildEnvironment(config);
    }

    // Write collection
    const collectionPath = path.resolve("${outputDir.replace(/\\/g, '/')}", "collection.json");
    fs.writeFileSync(collectionPath, JSON.stringify(collection, null, 2));
    console.log("Collection saved to: " + collectionPath);

    // Write environment
    if (environment) {
      const envPath = path.resolve("${outputDir.replace(/\\/g, '/')}", "environment.json");
      fs.writeFileSync(envPath, JSON.stringify(environment, null, 2));
      console.log("Environment saved to: " + envPath);
    }

    process.exit(0);
  } catch (err) {
    console.error("Error:", err.message || err);
    process.exit(1);
  }
}

function buildEnvironment(config) {
  return {
    id: crypto.randomUUID(),
    name: config.app?.name + " - ${options.env}",
    values: [
      { key: "baseUrl", value: "http://localhost:" + (config.port || 3000), enabled: true },
      { key: "apiVersion", value: "v1", enabled: true }
    ]
  };
}

function buildCollectionFromRoutes(routes, config) {
  // Basic collection structure
  return {
    info: {
      name: config.app?.name || "Wecon API",
      description: "Generated by Wecon CLI",
      schema: "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
    },
    item: [],
    variable: [
      { key: "baseUrl", value: "http://localhost:" + (config.port || 3000) }
    ]
  };
}

generate();
`;

      // Create a temporary script
      const tempScriptPath = path.join(projectRoot, ".wecon-postman-gen.ts");
      fs.writeFileSync(tempScriptPath, scriptContent);

      spinner.text = "Executing generation script...";

      // Execute using project's tsx
      const tsxPath = path.join(projectRoot, "node_modules", ".bin", "tsx");
      
      try {
        if (!fs.existsSync(tsxPath)) {
          execSync(`npx tsx ${tempScriptPath}`, { stdio: 'inherit' });
        } else {
          execSync(`${tsxPath} ${tempScriptPath}`, { stdio: 'inherit' });
        }
      } finally {
        // Cleanup
        fs.removeSync(tempScriptPath);
      }

      spinner.succeed("Postman collection generated!");
      console.log(chalk.green(`\nFiles saved to: ${outputDir}`));

    } catch (error) {
      spinner.fail("Failed to generate Postman collection");
      console.error(chalk.red((error as Error).message));
      
      // Cleanup if failed
      const tempScriptPath = path.join(process.cwd(), ".wecon-postman-gen.ts");
      if (fs.existsSync(tempScriptPath)) fs.removeSync(tempScriptPath);
    }
  });
